import bg from '../../assets/images/articleBg.png'

const articleList = [
    {
        title: 'XXXXXXXXXXXXXXXXXXXXX',
        href: '',
        image: bg,
        tag: '政会通',
        content: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...'
    },
    {
        title: 'XXXXXXXXXXXXXXXXXXXXX',
        href: '',
        image: bg,
        tag: '政会通',
        content: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...'
    },
    {
        title: 'XXXXXXXXXXXXXXXXXXXXX',
        href: '',
        image: bg,
        tag: '政会通',
        content: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...'
    }
]

export default articleList